import os, sys

# Add path to project root to access dapi module
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from typing      import Optional

from lib              import O
from .location_schema import LocationSchema


class StorySchema(O):
	id          : str = O.Field(default='', description='Id of the story. Autogenerated')
	title       : str = O.Field(default='', description='Title of the story')
	variation   : str = O.Field(default='', description='Variation of story title')
	idea        : str = O.Field(default='', description='Short summary of the story')
	genre       : str = O.Field(default='', description='Genre of the story')
	locations   : list[LocationSchema]